apiVersion: v2
name: litellm
description: A Helm chart to refer the official litellm helm chart
type: application
version: 0.7.0
dependencies:
  - name: litellm-helm
    version: 1.83.14-stable.patch.3
    repository: oci://ghcr.io/berriai
    condition: litellm-helm.enabled
