apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: amazee-ai-0.0.12
  namespace: kcm-system
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: amazee-ai
      version: 0.0.12-provisioner-examples
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: amazeeai-k0rdent-catalog
