apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: litellm-0.4.12
  namespace: kcm-system
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: litellm
      version: 0.4.12
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: amazeeai-k0rdent-catalog
