apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: litellm-0.4.0
  namespace: kcm-system
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: litellm
      version: 0.4.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: amazeeai-k0rdent-catalog