apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amazee-ai
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: amazee-ai-tls
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: amazee-ai
            port:
              name: http