apiVersion: db.amazee.ai/v1alpha1
kind: VectorDBClaim
metadata:
  name: vector-db-ir1
spec:
  # Required parameter - AWS region
  location: eu-west-1

  # Optional parameters with defaults
  engineVersion: "16.6"
  minCapacity: 0.5
  maxCapacity: 16
  databaseName: "vectordb"
  masterUsername: "postgres"
  backupRetentionPeriod: 7
  backupWindow: "06:42-07:12"
  maintenanceWindow: "wed:04:35-wed:05:05"
  deletionProtection: true
  generatePassword: true
