# 0. Wait for Crossplane and Terraform provider to be ready before creating custom resources
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-crossplane
  namespace: crossplane-system
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: crossplane
      containers:
      - name: wait
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for Crossplane to be ready..."
          kubectl wait --for=condition=available --timeout=300s deployment/crossplane -n crossplane-system
          kubectl wait --for=condition=available --timeout=300s deployment/crossplane-rbac-manager -n crossplane-system
          echo "Crossplane is ready!"

          echo "Waiting for Terraform provider CRDs to be available..."
          kubectl wait --for=condition=established --timeout=300s crd/providerconfigs.tf.upbound.io
          kubectl wait --for=condition=established --timeout=300s crd/workspaces.tf.upbound.io
          echo "Terraform provider CRDs are ready!"
      restartPolicy: Never
  backoffLimit: 3

---
# 1. Composite Resource Definition (XRD) - must be created first
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: vectordbs.db.amazee.ai
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  group: db.amazee.ai
  names:
    kind: VectorDB
    plural: vectordbs
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              location:
                type: string
                description: "AWS region for the vector database"
              envSuffix:
                type: string
                description: "Environment suffix for the vector database"
              engineVersion:
                type: string
                default: "16.6"
                description: "Aurora PostgreSQL engine version"
              minCapacity:
                type: number
                default: 2
                description: "Minimum ACU for Serverless v2"
              maxCapacity:
                type: number
                default: 16
                description: "Maximum ACU for Serverless v2"
              masterUsername:
                type: string
                default: "postgres"
                description: "Master database username"
              backupRetentionPeriod:
                type: integer
                default: 7
                description: "Days to retain backups"
              backupWindow:
                type: string
                default: "06:42-07:12"
                description: "Daily backup window"
              maintenanceWindow:
                type: string
                default: "wed:04:35-wed:05:05"
                description: "Weekly maintenance window"
              deletionProtection:
                type: boolean
                default: true
                description: "Enable deletion protection"
            required:
            - location
    served: true
    referenceable: true
  claimNames:
    kind: VectorDBClaim
    plural: vectordb-claims

---
# 2. AWS Credentials Secret - must be created before provider config
# Note: Update this secret with real AWS credentials after deployment
# apiVersion: v1
# kind: Secret
# metadata:
#   name: aws-creds
#   namespace: crossplane-system
#   annotations:
#     description: "Update this secret with real AWS credentials after deployment"
#     helm.sh/hook: post-install,post-upgrade
#     helm.sh/hook-weight: "2"
#     helm.sh/hook-delete-policy: hook-succeeded
# type: Opaque
# stringData:
#   credentials: |
#     [default]
#     aws_access_key_id = "changeme"
#     aws_secret_access_key = "changeme"
#
---
# 3. Terraform Provider Configuration - must be created after secret
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider-config
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  credentials:
  - filename: aws-creds.txt
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: credentials

---
# 4. Composition - must be created after XRD, secret, and provider config
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aws-vectordb
  labels:
    provider: aws
    vpc: "true"
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "4"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  compositeTypeRef:
    apiVersion: db.amazee.ai/v1alpha1
    kind: VectorDB
  writeConnectionSecretsToNamespace: crossplane-system
  mode: Pipeline
  pipeline:
  - step: create-vectordb
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: aws-vectordb
        base:
          apiVersion: tf.upbound.io/v1beta1
          kind: Workspace
          spec:
            providerConfigRef:
              name: aws-provider-config
            forProvider:
              source: Remote
              module: "github.com/amazeeio/amazeeai-k0rdent-catalog//terraform/vector-db?ref=crossplane-terraform"
              vars:
                - key: region
                  value: "eu-central-1"
                - key: environment_suffix
                  value: "prod"
                - key: postgres_cluster_name
                  value: "vectordb"
                - key: postgres_cluster_min_capacity
                  value: "2"
                - key: postgres_cluster_max_capacity
                  value: "16"
                - key: postgres_cluster_backup_window
                  value: "06:42-07:12"
                - key: postgres_cluster_maintenance_window
                  value: "wed:04:35-wed:05:05"
                - key: postgres_cluster_backup_retention_period
                  value: "7"
                - key: postgres_cluster_deletion_protection
                  value: "true"
                - key: postgres_cluster_engine_version
                  value: "16.6"
                - key: postgres_cluster_master_username
                  value: "postgres"
                - key: tags
                  value: '{"Environment":"production","ManagedBy":"crossplane"}'
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.location
          toFieldPath: spec.forProvider.vars[0].value
        - type: FromCompositeFieldPath
          fromFieldPath: spec.envSuffix
          toFieldPath: spec.forProvider.vars[1].value
        - type: FromCompositeFieldPath
          fromFieldPath: spec.minCapacity
          toFieldPath: spec.forProvider.vars[2].value
        - type: FromCompositeFieldPath
          fromFieldPath: spec.maxCapacity
          toFieldPath: spec.forProvider.vars[3].value
        - type: FromCompositeFieldPath
          fromFieldPath: spec.backupWindow
          toFieldPath: spec.forProvider.vars[4].value
        - type: FromCompositeFieldPath
          fromFieldPath: spec.maintenanceWindow
          toFieldPath: spec.forProvider.vars[5].value
        - type: FromCompositeFieldPath
          fromFieldPath: spec.backupRetentionPeriod
          toFieldPath: spec.forProvider.vars[6].value
        - type: FromCompositeFieldPath
          fromFieldPath: spec.deletionProtection
          toFieldPath: spec.forProvider.vars[7].value
        - type: FromCompositeFieldPath
          fromFieldPath: spec.engineVersion
          toFieldPath: spec.forProvider.vars[8].value
        - type: FromCompositeFieldPath
          fromFieldPath: spec.masterUsername
          toFieldPath: spec.forProvider.vars[9].value
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
        connectionDetails:
        - name: cluster_endpoint
          type: FromConnectionSecretKey
          fromConnectionSecretKey: cluster_endpoint
        - name: cluster_reader_endpoint
          type: FromConnectionSecretKey
          fromConnectionSecretKey: cluster_reader_endpoint
        - name: cluster_id
          type: FromConnectionSecretKey
          fromConnectionSecretKey: cluster_id
        - name: master_password
          type: FromConnectionSecretKey
          fromConnectionSecretKey: master_password
        - name: vpc_id
          type: FromConnectionSecretKey
          fromConnectionSecretKey: vpc_id
        - name: database_subnet_group_name
          type: FromConnectionSecretKey
          fromConnectionSecretKey: database_subnet_group_name