apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: litellm-0.1.642
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: 0.1.642
      version: 0.1.642
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: amazeeai-k0rdent-catalog
