apiVersion: v2
name: amazee-ai
description: A Helm chart to refer the official amazee.ai helm chart
type: application
version: 0.0.9
dependencies:
  - name: amazee-ai
    version: 0.0.6
    repository: oci://ghcr.io/amazeeio/amazee.ai
    condition: amazee-ai.enabled
  - name: postgresql
    version: 16.7.12
    repository: https://charts.bitnami.com/bitnami
    condition: amazee-ai.postgresql.enabled
  - name: prometheus
    version: 27.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: amazee-ai.prometheus.enabled
  - name: grafana
    version: 8.12.0
    repository: https://grafana.github.io/helm-charts
    condition: amazee-ai.grafana.enabled
