apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: amazeeai-global-provisioner
  namespace: kcm-system
spec:
  config:
    controlPlane:
      instanceType: t3.medium
      imageLookup:
        org: "137112412989"
    region: eu-central-2
    worker:
      instanceType: t3.medium
      rootVolumeSize: 60
      imageLookup:
        org: "137112412989"
  credential: aws-cluster-identity-cred
  serviceSpec:
    priority: 100
    services:
      - name: ingress-nginx
        namespace: ingress-nginx
        template: ingress-nginx-4-12-1
        values: |
          ingress-nginx:
            controller:
              config:
                use-proxy-protocol: "true"
                use-forwarded-headers: "true"
              service:
                annotations:
                  service.beta.kubernetes.io/aws-load-balancer-type: "classic"
                  service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      - name: cert-manager
        namespace: cert-manager
        template: cert-manager-1-17-1
        values: |
          cert-manager:
            crds:
              enabled: true
      - name: litellm
        namespace: litellm
        template: litellm-0.4.0
        values: |
          host: dummy-host
          litellm-helm:
            enabled: false
          prometheus:
            enabled: false
          grafana:
            enabled: false
      - name: amazee-ai
        namespace: amazee-ai
        template: amazee-ai-0.0.7
        values: |
          amazee-ai:
            enabled: true
            postgresql:
              enabled: false
              external:
                enabled: true
                  url: "postgresql://posgres:fillme@database-location:5432/postgres"
            backend:
              enabled: true
              replicas: 2
              database:
                  url: "postgresql://posgres:fillme@database-location:5432/postgres"
              env_suffix: "development"
              aws_access_key_id: "fillme"
              aws_secret_access_key: "fillme"
              ses_sender_email: "fillme"
              dynamodb_region: "fillme"
              ses_region: "fillme"
              stripe_secret_key: "fillme"
              secret_key: "supersecurepasswordkey"
              enable_metrics: true
              passwordlessSignIn: false
              enableLimits: false
            frontend:
              enabled: true
              replicas: 2
              stripe_publishable_key: "fillme"
              passwordlessSignIn: false
              apiUrl: "https://api.amazeeai.pippah.co.za"
            ingress:
              enabled: true
              hosts:
                - host: api.amazeeai.pippah.co.za
                  paths:
                    - path: /
                      pathType: Prefix
                      port: 8800
              tls:
                - secretName: api-amazeeai-pippah-co-za-tls
                  hosts:
                    - api.amazeeai.pippah.co.za
            frontendIngress:
              enabled: true
              hosts:
                - host: amazeeai.pippah.co.za
                  paths:
                    - path: /
                      pathType: Prefix
                      port: 3000
              tls:
                - secretName: amazeeai-pippah-co-za-tls
                  hosts:
                    - amazeeai.pippah.co.za

  template: aws-standalone-cp-0-2-1