apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: crossplane-resources
  namespace: k0rdent
spec:
  config:
    controlPlane:
      instanceType: t3.medium
      imageLookup:
        org: "137112412989" # Verify this if changing the region
    region: eu-west-1 # Using ireland for now
    worker:
      instanceType: t3.medium
      rootVolumeSize: 60
      imageLookup:
        org: "137112412989"
  credential: aws-cluster-identity-cred
  serviceSpec:
    priority: 100
    services:
      - name: crossplane
        namespace: crossplane-system
        template: crossplane-0.2.2
        values: |
          crossplane:
            enabled: true
            function:
              packages:
                - "xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform:v0.8.2"
                - "ghcr.io/amazeeio/amazeeai-k0rdent-catalog/vectordb-function:v0.0.25-crossplane"
            provider:
              packages:
                - "xpkg.crossplane.io/crossplane-contrib/provider-family-aws:v1.23.0" # top level provider for credential management
                - "xpkg.crossplane.io/crossplane-contrib/provider-terraform:v0.21.0"
                - "xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2:v1.23.0" # Need EC2 for VPC management
                - "xpkg.crossplane.io/crossplane-contrib/provider-aws-rds:v1.23.0" # RDS is for DB cluster creation
                - "xpkg.crossplane.io/crossplane-contrib/provider-aws-iam:v1.23.0" # IAM is for DB monitoring role

  template: aws-standalone-cp-1-0-10
