apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: crossplane-system
  annotations:
    description: "Update this secret with real AWS credentials after deployment"
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = "changeme"
    aws_secret_access_key = "changeme"