apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: amazee-ai-mothership
  namespace: k0rdent
spec:
  config:
    controlPlane:
      instanceType: t3.medium
      imageLookup:
        org: "137112412989" # If you're running in an opt-in or special region change this
    region: eu-central-1
    worker:
      instanceType: t3.medium
      imageLookup:
        org: "137112412989"
  credential: aws-cluster-identity-cred
  template: aws-standalone-cp-0-0-5