apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: amazee-ai-mothership
  namespace: k0rdent
spec:
  config:
    controlPlane:
      instanceType: t3.medium
      imageLookup:
        org: "012345678901"
    region: eu-central-1
    worker:
      instanceType: t3.medium
      imageLookup:
        org: "012345678901"
  credential: aws-cluster-identity-cred
  template: aws-standalone-cp-0-0-5