lago:
  apiUrl: https://lago-api.example.com
  frontUrl: https://lago.example.com
  # TODO use manged postgres and redis and disable here
  postgresql:
    enabled: true
  redis:
    enabled: true
  global:
    postgresql:
      image:
        tag: 16.6.6
    segment:
      enabled: false
    signup:
      enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: "letsencrypt-prod"
      className: nginx
      apiHostname: lago-api.example.com
      frontHostname: lago.example.com
  minio:
    enabled: true
    replicas: 2          
    fullnameOverride: "lago-minio"  # Matches the release name
    buckets:
      - name: "lago-minio"          # Matches the fullnameOverride
        policy: none
        purge: false
        versioning: false
        objectlocking: false
    endpoint: "http://minio.amazeeai-temp1.amazeeio.review"          
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/issuer: "letsencrypt-prod"
      path: /
      hosts:
        - minio.amazeeai-temp1.amazeeio.review
      tls: 
        - hosts:
          - minio.amazeeai-temp1.amazeeio.review
          secretName: lago-minio-tls   