apiVersion: v2
name: litellm-service-template
description: k0rdent service template for "litellm"
type: application
version: 0.1.642
appVersion: "0.1.642"
dependencies:
  - name: amazeeai-k0rdent-catalog
    version: 1.0.0
    repository: oci://ghcr.io/amazeeio/amazeeai-k0rdent-catalog/charts
